OS-8334 Bring OpenSSL 3 to the platform
joyent/kbmd pull request #19
Opened 2021-11-10 20:22 UTC by danmcd

This changeset is to make sure kbmd uses the OpenSSL 1.0.2 versions of things.

2021-11-12 21:12 UTC, bahamat approved these changes

2021-11-12 21:22 UTC, danmcd commented
NOTE: This PR must not be integrated until joyent/illumos-extra#61 is.

2021-12-06 23:17 UTC, bahamat requested changes
Makefile needs copyright update

2021-12-07 04:00 UTC, danmcd commented
> Makefile needs copyright update

Fixed.

2021-12-07 04:27 UTC, papertigers approved these changes

2021-12-07 04:40 UTC, bahamat approved these changes

2021-12-07 20:18 UTC, merged